# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{polyglot}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mlomnicki"]
  s.date = %q{2009-10-22}
  s.default_executable = %q{polyglot}
  s.email = %q{michal@lomnicki.com.pl}
  s.executables = ["polyglot"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/polyglot",
     "lib/polyglot.rb",
     "lib/polyglot/cyclic_hash.rb",
     "lib/polyglot/dict.yml",
     "lib/polyglot/dictionary.rb",
     "lib/polyglot/polyglot.glade",
     "lib/polyglot/polyglot_glade.rb",
     "lib/polyglot/utils.rb"
  ]
  s.homepage = %q{http://github.com/mlomnicki/polyglot}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Easy GTK application which helps you to learn new language by asking you for a word in one language and you must answer in another.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
